# Generated by Django 5.1.6 on 2025-02-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_images_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_path',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
