# Generated by Django 5.1.6 on 2025-02-20 15:43

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_images_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_path',
            field=models.ImageField(upload_to=images.models.image_upload_path),
        ),
    ]
