# Generated by Django 5.1.6 on 2025-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
