# Generated by Django 5.1.6 on 2025-02-16 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(max_length=15)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('user_password', models.TextField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='images.images')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.level')),
            ],
        ),
    ]
