# Generated by Django 5.1.6 on 2025-02-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image_rul',
        ),
    ]
