# Generated by Django 5.1.6 on 2025-03-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.JSONField()),
                ('image', models.ImageField(upload_to='')),
                ('example', models.TextField()),
                ('drag_and_drop', models.JSONField()),
            ],
        ),
    ]
