# Generated by Django 5.1.6 on 2025-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_remove_messages_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='conversation_id',
            field=models.CharField(default='default_conversation', max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='topic',
            field=models.TextField(max_length=50),
        ),
    ]
