# Generated by Django 5.1.6 on 2025-02-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_messages_conversation_id_alter_messages_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='topic',
            field=models.TextField(default='introduce yourself', max_length=50),
        ),
    ]
