# Generated by Django 5.1.6 on 2025-02-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_alter_messages_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='topic',
            field=models.TextField(default='if user dont ask anything, introduce yourself', max_length=50),
        ),
    ]
