# Generated by Django 5.1.6 on 2025-03-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_alter_messages_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.JSONField()),
            ],
        ),
    ]
