# Generated by Django 5.1.6 on 2025-03-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0007_feedback_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='conversation',
            field=models.TextField(),
        ),
    ]
