# Generated by Django 5.1.6 on 2025-03-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0008_alter_feedback_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='topic',
        ),
    ]
